### ISSUE TITLE
Causes total character lockdown after recent game update

### ISSUE THREAD

**Issue by Astral-Crescent** [afilbert/valheim-toggle-movement-mod#12]
As the title says. Now when equipping a weapon, cannot move or do anything. Only with this mod, affecting myself and others I know. This game is unplayable without this mod for me. Please fix.

**Comment by afilbert** [comment]
I've been on the road, so haven't had a chance to check out the updates or anything. I'll be able to take a look over the weekend for sure. I can't anticipate how long its going to take until I dive into the new assemblies, but I'll update the thread here when I have an idea. Thanks for posting!

**Comment by afilbert** [comment]
Uploaded the fix in version 0.1.1 to both Thunderstore and Nexus. That should resolve this issue.

**Comment by afilbert** [comment]
Fixed in #13
