### ISSUE TITLE
Major Issues

### ISSUE THREAD

**Issue by RolePlayerVintage** [afilbert/valheim-toggle-movement-mod#14]
So toggling AutorunToggle off disable autorun entirely when the tip specifies that this option only toggles whether autorun follows the cursor or not.

SprintToggle for toggling whether the sprint key is a toggle or hold-key does not work at all.

SprintAlternate does not function.

**Comment by RolePlayerVintage** [comment]
After a lot more testing I figured out where I was going wrong with SprintToggle and SprintAlternate however, AutorunToggle still does not function

**Comment by afilbert** [comment]
It’s likely that the last major Valheim update changed the core logic, so the mod is going to have to come up-to-speed. I’m planning to dive in and fix things soon. Stay tuned, and thanks for reporting!

**Comment by afilbert** [comment]
This issue should be resolved @RolePlayerVintage! Releases are avail in both [Thunderstore](https://valheim.thunderstore.io/package/GetOffMyLawn/ToggleMovementMod/) and [Nexus](https://www.nexusmods.com/valheim/mods/2367?tab=files). Please feel free to reopen if that didn't do the trick for you.
