### ISSUE TITLE
typing in chat still triggers mod keybinds

### ISSUE THREAD

**Issue by nbusseneau** [afilbert/valheim-toggle-movement-mod#20]
Hey, thanks for your mods!

When typing in the chat, mod keybinds are still registered (example: type `Q` and the autorun will trigger). Ideally keybinds would not get registered when input is grabbed by the chat, like the regular game keybinds. This would avoid both doing things you didn't mean to when trying to chat, and allow to chat while the autorun is doing its thing 😄

**Comment by afilbert** [comment]
Also great feedback! I never use the chat, so never thought about it. Thanks for checking out my mod and taking the time to create these issues!

**Comment by nbusseneau** [comment]
Not opening a new issue because I think this is a variant of this one: if you enable `AutorunInInventory`, then mod keybinds also get triggered while the inventory is open.

Now if you have the vanilla keybinds of `LeftShift` for sprint and `LeftCtrl` for crouching/sneaking, then when you open the inventory (or a chest, because that's inventory as well) and try to split stack (`LeftShift` + `LeftClick`) or drop/transfer (`LeftCtrl` + `LeftCtrl`) items, then the sprint status is toggled on/off and the crouch status is toggled on/off (because of `RunToCrouchToggle` being enabled by default in the config, so it intercepts crouching as well, haha).

Discovered this yesterday because I was confused as to why my character was now suddenly crouching/standing up all the time while I was interacting with chests (I use the transfer keybind all the time) :D

> Thanks for checking out my mod and taking the time to create these issues!

Happy to contribute, let me know if you want to me to test an early build or something, also can look into submitting a PR if you want :)

**Comment by afilbert** [comment]
I think I have a good [solution ](https://github.com/afilbert/valheim-toggle-movement-mod/pull/23) for the chat issue, but I'm not able to reproduce the inventory stuff. I have some other mods that might also be interfering with my ability to reproduce, though, so that might be part of it. That said, I'm happy to review a PR if you wanna take a crack at it! And thanks for offering!

**Comment by nbusseneau** [comment]
> but I'm not able to reproduce the inventory stuff

Could it be it was fixed incidentally as part of addressing the chat issue? I haven't looked at the PR yet but I can try a local build and see if I still reproduce the issue later, at least with the current build on Thunderstore I can reproduce it easily (clean profile, no other mods).

**Comment by nbusseneau** [comment]
Can still reproduce with build off of `version-1-3-0` branch, here's a quick example of how to reproduce with `LeftCtrl` when a chest is open (conflict between crouch and transfer), but can also do this with `LeftCtrl` with just inventory (conflict between crouch and drop) or `LeftShift` with either inventory or chest (used for both sprint and split stack).

https://github.com/afilbert/valheim-toggle-movement-mod/assets/4659919/f49c0f91-5eb9-4b00-96f6-90f364eef6d9

**Comment by nbusseneau** [comment]
Seems like input is correctly ignored when chat is open though 😄

**Comment by afilbert** [comment]
Thanks for pulling that down and testing, @nbusseneau! 🙏 It's gotta be something else in my mods list that's capturing that input. Lemme see if I can push another commit and get that fixed. I'm gonna strip my dev env down to just this mod and try again.

**Comment by afilbert** [comment]
Ok, just pushed another [commit](https://github.com/afilbert/valheim-toggle-movement-mod/pull/23/commits/e2446552a470e10b6462df79b09e9a0c1b4254f2). This one should take care of it. I'll wanna test a lil more before merging and publishing.

**Comment by nbusseneau** [comment]
Confirm this new version fixes the inventory conflict, can't reproduce anymore :)

Noticed another small thing that conflicts, let me know if you want me to open another issue: when pressing Escape to close a menu (inventory, minimap, chat), the autorun is cancelled. This does not happen when closing the menu without Escape (e.g. closing inventory with Tab, minimap with M, chat with Enter), and in vanilla Escape does not cancel autorun when pressing Escape to close any menu. This is useful especially for chat because otherwise the only way to cancel a message without sending it is to press Down to clear it and then Enter to close the chat, so not very intuitive compared to Escape.

(And if you end up implementing something for #21, let me know as well :D)

**Comment by afilbert** [comment]
Up to you if you wanna open another issue, but I'm fine solving as part of this one. That Esc behavior is originally by design, but I think it would make sense to add another config option for if it shouldn't interrupt autorun. Here's that: [9ced796](https://github.com/afilbert/valheim-toggle-movement-mod/pull/23/commits/9ced796f14a054ea9df00de5b4aaca39fb123dcb)

**Comment by afilbert** [comment]
> And if you end up implementing something for https://github.com/afilbert/valheim-toggle-movement-mod/issues/21

That should be available in #23! It comes in the form for two new config options:

* AutorunDisableOnInput
* AutorunDisableOnNoStam

It doesn't explicitly measure whether the character comes to a stop on its own, rather opting to disable on any directional input. I _think_ that's what you're looking for, but lemme know if it's missing the mark.

**Comment by nbusseneau** [comment]
> Up to you if you wanna open another issue, but I'm fine solving as part of this one. That Esc behavior is originally by design, but I think it would make sense to add another config option for if it shouldn't interrupt autorun. Here's that: [9ced796](https://github.com/afilbert/valheim-toggle-movement-mod/pull/23/commits/9ced796f14a054ea9df00de5b4aaca39fb123dcb)

Huh, interesting, I'm curious now: why did you design it explicitly like this? 🤔 I genuinely would have thought this to be a bug same as the chat thingy, because of how it conflicts with vanilla UI itself 😄

**Comment by afilbert** [comment]
If memory serves, I think I was surprised while testing that I kept running after I hit Esc... so I built it in.

**Comment by nbusseneau** [comment]
Haha, I guess you might not use Escape to close menus 😄

**Comment by nbusseneau** [comment]
Found another variant of this one: if you open the build menu with any tool (Hammer, Hoe, Cultivator), autorun's `Q` keybind conflicts with the "Cycle snapping" keybind.

**Comment by afilbert** [comment]
Nice catch! Fix here: [f4847c1](https://github.com/afilbert/valheim-toggle-movement-mod/pull/23/commits/f4847c1f98336cae7ebf32ac41c3e6acf41e3dc6)

**Comment by nbusseneau** [comment]
Confirm I can't reproduce this now.

**Comment by afilbert** [comment]
Thanks for all your collaboration, and for testing and reviewing the PR! 🙏
