### ISSUE TITLE
feature request: add config option to disable sprinting when coming to a halt

### ISSUE THREAD

**Issue by nbusseneau** [afilbert/valheim-toggle-movement-mod#21]
Hey,

In vanilla, the auto-run option (which functions as a sprint toggle) automatically disables sprinting when the character comes to a halt, e.g. you start moving, toggle sprint, then stop giving movement orders WASD => at this point if you resume movement orders, sprint is not enabled.

![image](https://github.com/afilbert/valheim-toggle-movement-mod/assets/4659919/f2bb0071-6cb1-4a1d-832e-7e073450b932)

I would personally like it if ToMoMo had a config option to do the same, i.e. disable sprint on halt, as I find it more natural and is something I'm more used to both from Valheim vanilla and also from other games 😄

**Comment by afilbert** [comment]
Great suggestion! I'll see what I can whip up.

**Comment by nbusseneau** [comment]
Moving the answer to https://github.com/afilbert/valheim-toggle-movement-mod/issues/20#issuecomment-2185420982 here since it's the proper issue:

> > And if you end up implementing something for #21
> 
> That should be available in #23! It comes in the form for two new config options:
>
> * AutorunDisableOnInput
> * AutorunDisableOnNoStam
>
> It doesn't explicitly measure whether the character comes to a stop on its own, rather opting to disable on any directional input. I _think_ that's what you're looking for, but lemme know if it's missing the mark.

Haha, yeah indeed this is not what I meant 😁 Actually I must admit I'm not quite sure what you wanted to do with these new config options:

- For `AutorunDisableOnInput` the use case is clear, however AFAICT autorun was already disabled on any directional input in ToMoMo: it's just that by default `AutorunStrafe` is enabled, however if you disable `AutorunStrafe` you end up with the same behaviour as with `AutorunDisableOnInput` enabled.
- As for `AutorunDisableOnNoStam` I can't really think of any actual use case for it, it seems superfluous to me as well.

So all in all I would say probably if I were to make a decision I would not add these to the mod.

Anyway, my OP above was not about autorun but about the sprint toggle (which vanilla confusingly labels auto-run in the screenshot above, but as you can see from the description it is indeed the sprint toggle and not the autorun. It is doubly confusing because they DO label autorun properly in keybinds). Here is how the vanilla sprint toggle behaves:

https://github.com/afilbert/valheim-toggle-movement-mod/assets/4659919/119b9260-b1a7-447c-9262-b6ad8ebb076d

- The input sequence is: Hold `W` (forward) > Press `Shift` (sprint) once > stop holding `W` > repeat.
- The sprint stays toggled on after `Shift` is pressed because the `auto-run` option screenshot in OP is ticked: if not ticked, then you have to hold `Shift`.
- Notice how the sprint toggle is automatically disabled every time we stop holding `W`, i.e. when the character comes to a halt due to no movement input.

This pattern here where sprint can be toggled on/off at will with `Shift` while a movement occurs, but the sprint is automatically toggled off when movement stops, is the thing I'd like to have (I may be wrong but I think this to be the standard sprint toggle implementation, at least in all of the games I play the sprint toggle behaves like this, so you can understand my surprise when ToMoMo keeps sprint toggled on even if you stop moving 😄).

**Comment by afilbert** [comment]
Thanks for the clarification! And you're right that we already get that behavior if the strafe option is disabled. I didn't think of that when adding the new config. I feel the same about the no-stam option, too. I'm not sure it really serves a purpose. 

I'll think a lil more about how this functions... because we may be able to simply shortcut it to using the so-called "Auto-run" toggle in the settings. Maybe unchecking the OverrideGameAutorun will suffice. I'll have to play around with it a bit, but there's perhaps even more opportunity to simplify.

**Comment by afilbert** [comment]
Ok, I think I've got a good solution pushed [here](https://github.com/afilbert/valheim-toggle-movement-mod/pull/23/commits/9c6845e95140fa8a7396d3560923d03d7065122f). It cleans up redundant config (please see commit message) and should allow the behavior this issue is requesting _while_ preserving/enhancing past behavior.

Namely, it allows users to individually toggle off the Sprint/Auto-run features of the mod, while allowing progressive enhancement of the stock game behavior; depending on config settings.

So to get this issue's desired behavior, you can turn off the `AutorunStrafe` and `SprintToggle` config options, and enable the game's vanilla "Auto-run" setting after #23 is merged and published. 

Lemme know what you think!

**Comment by nbusseneau** [comment]
Just tried the latest version built off branch `version-1-3-0`: I might be missing something but I don't see the difference, it seems to behave exactly like on current live version when disabling `SprintToggle` and letting the vanilla "auto-run" do the toggling instead.

In effect this means stamina bar coloring and stamina safeguard are not working at all, as both of these seem to be dependent on `SprintToggle` still. (By the way why do you say that `AutorunStrafe` should be disabled? AFAICT it has always worked even when the vanilla "auto-run" handles toggling 🤔).

**Comment by afilbert** [comment]
Yup, the latest commit cleans up redundant config that I'd layered on in response to the devs adding vanilla "auto-run." But I think I'm understanding a lil better. You're looking for the sprint behavior of the vanilla "auto-run" only with the benefit of the colors and stam safeguards? That should be fairly easy to accomplish, and I should be able to decouple it from reliance on the `SprintToggle` or `OnlyToggleWhenAutorunning` config. Would that satisfy this issue, or were you hoping for it in a completely separate config toggle?

I mentioned the `AutorunStrafe` if you were looking for the behavior of vanilla "auto-run" with some of the other the benefits that ToMoMo has to offer. Specifically, stock game will detoggle sprint and the real-deal auto-run on WASD input.

**Comment by nbusseneau** [comment]
> Would that satisfy this issue, or were you hoping for it in a completely separate config toggle?

I personally don't need it in a separate toggle, I think it's up to you whether or not you want to provide this 😉 

> I mentioned the AutorunStrafe if you were looking for the behavior of vanilla "auto-run" with some of the other the benefits that ToMoMo has to offer. Specifically, stock game will detoggle sprint and the real-deal auto-run on WASD input.

I think there is confusion again between vanilla auto-run and "auto-run" 🤔 

- The vanilla auto-run sucks, that's why ToMoMo is useful (😁) for example because of the fact you can strafe with ToMoMo.
- The vanilla "auto-run" is completely unrelated to auto-run, it's just a sprint toggle, except that it behaves differently to ToMoMo's sprint toggle in the sense that it detoggles sprinting when the character comes to a halt (which again is how sprint toggles usually work in most games, at least as far I can tell 😄) whereas ToMoMo's does not.

To rephrase again differently, as a user:
- Whether the sprint toggle is handled by vanilla "auto-run" or ToMoMo's sprint toggle doesn't matter much to me, as long as the sprint detoggles when the character comes to a halt.
- The "sprint detoggle" behaviour has no relation with any other ToMoMo feature: ideally all other features should work no matter how the sprint toggle behaves.

**Comment by nbusseneau** [comment]
(really Valheim naming that toggle "auto-run" instead of "sprint toggle" when they already had a keybind dedicated to auto-running aptly named auto-run was a very very bad idea, it generates so much confusion for absolutely no reason...)

**Comment by afilbert** [comment]
Agreed. Having two diff behaviors for "auto-run" is very confusing. 😅

**Comment by afilbert** [comment]
Ok, I believe [4b2499a](https://github.com/afilbert/valheim-toggle-movement-mod/pull/23/commits/4b2499af4c8a814162c00d1574ae7ece1337b117) should satisfy this issue.

**Comment by nbusseneau** [comment]
> default it to false to allow sprint behavior to follow principle of least astonishment

🤣

**Comment by nbusseneau** [comment]
Confirm sprint correctly is toggled off when coming to a halt! Noticed one issue while testing: stamina bar color does not go back to default color when sprinting is toggled off, it seems to stay orange on my end.

**Comment by afilbert** [comment]
Ok, sorry for the delay. I _almost_ had something Sunday night, but needed to test it for a bit. I didn't like my original solution using player's velocity. That changed the behavior in unexpected ways. Primarily, it meant that sprint toggled off if the character stopped even briefly against anything in the way. I'd prefer that the player keep running, for example, even if pressed up against a closed door or rock. Here's what I came up with [c741427](https://github.com/afilbert/valheim-toggle-movement-mod/pull/23/commits/c74142705de13e07a6889038f514471d6df719e6)

**Comment by nbusseneau** [comment]
No worries about the delay mate, you do your things, it's just a mod 😄 Trying it out!

**Comment by nbusseneau** [comment]
Yep, confirm this one works as expected:
- Sprint is correctly toggled off when coming to a halt, and also works when bumping into objects.
- The rest of the mod seems to work as it used to before (coloring, stam guards while autorunning, etc.)

Noticed one minor conflict between the mod and vanilla's "auto-run" (the sprint toggle one, the one screenshot at the beginning of the issue): if the "auto-run" is enabled in settings, both it and the mod's sprint toggle are cancelling out each other, and sprinting is back to being a hold instead of a toggle 😂

Maybe we should document in README / setting description that vanilla's "auto-run" should be unticked if using the mod's sprint toggle (or even better if somehow the mod could ignore vanilla's "auto-run" status entirely) 🤔 

In any case this looks great!

**Comment by afilbert** [comment]
Nice catch, I think I have it balanced now in [f4847c1](https://github.com/afilbert/valheim-toggle-movement-mod/pull/23/commits/f4847c1f98336cae7ebf32ac41c3e6acf41e3dc6). I also added some helpful text to the menus when the mod is enabled that describe what the vanilla Auto-run toggle is actually doing. Lemme know what you think!

![Screenshot 2024-07-17 002438](https://github.com/user-attachments/assets/d48642ea-9edb-4887-91d6-76cffcc91400)

**Comment by nbusseneau** [comment]
Confirm I can't reproduce the conflict above, it now works all the time (either if only vanilla's "auto-run" is enabled or only the mod's `SprintToggle` option is enabled, or both), and yeah, the hover text for that option does state exactly this (as pictured in OP) but I also think having it marked explicitly like this is good!

**Comment by afilbert** [comment]
Ok @nbusseneau, I think I have this settled. Updated README. If you'd be so kind as to give #23 a review, I'd appreciate it! Thanks so much for pulling this down and helping me test it so thoroughly.
