### ISSUE TITLE
bug: sprint toggle sometimes "flicker"

### ISSUE THREAD

**Issue by nbusseneau** [afilbert/valheim-toggle-movement-mod#24]
Hey, been playing with the new version of the mod on our dedicated server and all the changes you made were well received -- people had been complaining about the various things (e.g. crouching while transferring items to chests haha) and all of these are gone.

There's one remaining complaint which I hadn't reported earlier because I wasn't sure yet if it was ToMoMo-induced: sometimes, the sprint toggle will "flicker" when you try to enable it.

Say, you are currently auto-running, and you try to toggle sprint on: it toggles on and then off immediately (we see the stamina bar flashing color changes immediately), as if either it was "double tapping" the toggle, or as if the toggle was "invisibly on" and we were toggling it off instead of on. When in this state, it will generally be stuck for a good number of attempts, until it works again.

Multiple users (including myself) have experienced this, but so far we haven't been able to find neither a reliable reproduction cause, neither a reliable workaround / fix... 😕 

Putting it out here just in case you have an idea already, and otherwise will report back if we do find something.

**Comment by afilbert** [comment]
Thanks for reporting. I'd be curious to know what other mods you typically run alongside ToMoMo. I could see this being a sync issue between the Update method (where I'm setting global state) and the SetControls method patch. I may try to trigger that state from SetControls entirely instead of setting that from the global Update loop.

**Comment by nbusseneau** [comment]
Unfortunately I don't think it is related to any other mod as I have experienced this issue as well on a clean profile with only ToMoMo 😅 Still trying to figure out what triggers the issue.

**Comment by afilbert** [comment]
@nbusseneau apologies for the delay, I've got a fix and a new feature out in #25 if you wanna take a look.

**Comment by afilbert** [comment]
Closed by #25
