### ISSUE TITLE
Feature request: strafe while autorunning

### ISSUE THREAD

**Issue by Darrken** [afilbert/valheim-toggle-movement-mod#3]
Love the mod! Finally something to usurp [Better Autorun](https://valheim.thunderstore.io/package/Ragnar/Ragnars_Better_Autorun/) as my go-to. One thing I miss from that mod is the ability to strafe as I autorun without it breaking it. Any chance that's doable?

**Comment by afilbert** [comment]
Great suggestion! That's been [released](https://github.com/afilbert/valheim-toggle-movement-mod/releases/tag/v0.0.5). If you dig it, maybe think about a 👍 in the [Thunderstore page](https://valheim.thunderstore.io/package/GetOffMyLawn/ToggleMovementMod/).

**Comment by Darrken** [comment]
Awesome, thanks! I'd already upvoted it but I'd do it again if I could!
